[tool.black]
line-length = 80
target-version = ['py38']
exclude = '''

(
  /(
      \htmlcov       # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
